### ISSUE TITLE
Sauvegardes paramètres Eclipse

### ISSUE THREAD

**Issue by rudiger-isika** [Asali973/TripHub#2]
Pouvoir restaurer paramètres Java 11 / Apparence & Serveur au redémarrage

@zoubeidada merci pour votre precieuse aide

**Comment by zoubeidada** [comment]
Peux-tu me donner quelques exemples de paramètres importants !

Le ven. 28 juil. 2023 à 14:44, rudiger-isika ***@***.***> a
écrit :

**Comment by rudiger-isika** [comment]
résolu
